/* Generated By:JavaCC: Do not edit this line. TrabalhoSemanticoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TrabalhoSemanticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINECOMMENT = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSIF = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int FOREACH = 16;
  /** RegularExpression Id. */
  int FUNCTION = 17;
  /** RegularExpression Id. */
  int TYPE = 18;
  /** RegularExpression Id. */
  int PROCEDURE = 19;
  /** RegularExpression Id. */
  int CONSTANT = 20;
  /** RegularExpression Id. */
  int ENUM = 21;
  /** RegularExpression Id. */
  int BY = 22;
  /** RegularExpression Id. */
  int SWITCH = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int THEN = 25;
  /** RegularExpression Id. */
  int CASE = 26;
  /** RegularExpression Id. */
  int CONTINUE = 27;
  /** RegularExpression Id. */
  int RETRY = 28;
  /** RegularExpression Id. */
  int EXIT = 29;
  /** RegularExpression Id. */
  int TO = 30;
  /** RegularExpression Id. */
  int PROFILE = 31;
  /** RegularExpression Id. */
  int PROFILE_TIME = 32;
  /** RegularExpression Id. */
  int TRACE = 33;
  /** RegularExpression Id. */
  int BATCH = 34;
  /** RegularExpression Id. */
  int TYPE_CHECK = 35;
  /** RegularExpression Id. */
  int INLINE = 36;
  /** RegularExpression Id. */
  int WARNING = 37;
  /** RegularExpression Id. */
  int SAVE = 38;
  /** RegularExpression Id. */
  int RESTORE = 39;
  /** RegularExpression Id. */
  int STRICT = 40;
  /** RegularExpression Id. */
  int LOOP = 41;
  /** RegularExpression Id. */
  int GOTO = 42;
  /** RegularExpression Id. */
  int NOT = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int XOR = 46;
  /** RegularExpression Id. */
  int AS = 47;
  /** RegularExpression Id. */
  int LABEL = 48;
  /** RegularExpression Id. */
  int UNTIL = 49;
  /** RegularExpression Id. */
  int DOLAR = 50;
  /** RegularExpression Id. */
  int END = 51;
  /** RegularExpression Id. */
  int ALPHA = 52;
  /** RegularExpression Id. */
  int DIGITDEC = 53;
  /** RegularExpression Id. */
  int DIGITHEX = 54;
  /** RegularExpression Id. */
  int DIGITOCT = 55;
  /** RegularExpression Id. */
  int DIGITBIN = 56;
  /** RegularExpression Id. */
  int USCORE = 57;
  /** RegularExpression Id. */
  int SYMBOL = 58;
  /** RegularExpression Id. */
  int CHAR = 59;
  /** RegularExpression Id. */
  int ESCCHAR = 60;
  /** RegularExpression Id. */
  int STRING = 61;
  /** RegularExpression Id. */
  int IDENTIFIER = 62;
  /** RegularExpression Id. */
  int ATOMINTEGER = 63;
  /** RegularExpression Id. */
  int ATOMREAL = 64;
  /** RegularExpression Id. */
  int ATOMBINARY = 65;
  /** RegularExpression Id. */
  int ATOMOCTAL = 66;
  /** RegularExpression Id. */
  int ATOMDECIMAL = 67;
  /** RegularExpression Id. */
  int ATOMHEXADECIMAL = 68;
  /** RegularExpression Id. */
  int BIN = 69;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BLOCKCOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "<LINECOMMENT>",
    "\"else\"",
    "\"if\"",
    "\"elsif\"",
    "\"while\"",
    "\"break\"",
    "\"return\"",
    "\"for\"",
    "\"foreach\"",
    "\"function\"",
    "\"type\"",
    "\"procedure\"",
    "\"constant\"",
    "\"enum\"",
    "\"by\"",
    "\"switch\"",
    "\"do\"",
    "\"then\"",
    "\"case\"",
    "\"continue\"",
    "\"retry\"",
    "\"exit\"",
    "\"to\"",
    "\"profile\"",
    "\"profile_time\"",
    "\"trace\"",
    "\"batch\"",
    "\"type_check\"",
    "\"inline\"",
    "\"warning\"",
    "\"save\"",
    "\"restore\"",
    "\"strict\"",
    "\"loop\"",
    "\"goto\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"as\"",
    "\"label\"",
    "\"until\"",
    "\"$\"",
    "\"end\"",
    "<ALPHA>",
    "<DIGITDEC>",
    "<DIGITHEX>",
    "<DIGITOCT>",
    "<DIGITBIN>",
    "\"_\"",
    "<SYMBOL>",
    "<CHAR>",
    "<ESCCHAR>",
    "<STRING>",
    "<IDENTIFIER>",
    "<ATOMINTEGER>",
    "<ATOMREAL>",
    "<ATOMBINARY>",
    "<ATOMOCTAL>",
    "<ATOMDECIMAL>",
    "<ATOMHEXADECIMAL>",
    "<BIN>",
    "\"?\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"&\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"[\"",
    "\"]\"",
    "\"..\"",
    "\"{\"",
    "\"}\"",
  };

}
