/* Generated By:JavaCC: Do not edit this line. TrabalhoSemantico.java */
import java.util.*;

public class TrabalhoSemantico implements TrabalhoSemanticoConstants {

static Hashtable<Integer, Dado> TabelaSimb = new Hashtable<Integer, Dado>();
static Hashtable<Integer, Dado> TabelaAux = new Hashtable<Integer, Dado>();
static Integer indexTabela = 0;
static Integer nivelCorrente = 0;
static String flagCategoria = "";
static Integer flagBranchStmt = 0;
static Integer nReturn = 0, procedureReturn = 0;
static Dado dado = new Dado();
static ArrayList <Integer> listaChaves = new ArrayList <Integer> ();
static Token valor = null;

    public static void main(String[] args){
        try{
            TrabalhoSemantico t = new TrabalhoSemantico(new java.io.FileInputStream(args[0]));
            t.initBuiltins();
            t.Start();
//            System.out.println("-----------------------------------SIMB----------------------------------");
//            imprimeTabela(TabelaSimb);
//            System.out.println("-----------------------------------AUX-----------------------------------");
//            imprimeTabela(TabelaAux);
        } catch (java.io.FileNotFoundException ex) {
            System.out.println("Arquivo " + args[0] + " nao foi encontrado");
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        } catch (TokenMgrError ex) {
            System.out.println(ex.getMessage());
        }
    }

/* Programa */
  static final public void Start() throws ParseException {
    Stmtblk();
    jj_consume_token(0);
  }

  static final public void Stmtblk() throws ParseException {
    Statement();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case BREAK:
      case RETURN:
      case FOR:
      case FOREACH:
      case FUNCTION:
      case TYPE:
      case PROCEDURE:
      case CONSTANT:
      case ENUM:
      case SWITCH:
      case CONTINUE:
      case RETRY:
      case EXIT:
      case LOOP:
      case GOTO:
      case IDENTIFIER:
      case 70:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      Statement();
    }
  }

  static final public void Block() throws ParseException {
    Statementblock();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case BREAK:
      case RETURN:
      case FOR:
      case FOREACH:
      case CONSTANT:
      case ENUM:
      case SWITCH:
      case CONTINUE:
      case RETRY:
      case EXIT:
      case LOOP:
      case GOTO:
      case IDENTIFIER:
      case 70:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      Statementblock();
    }
  }

  static final public void Statement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BREAK:
      Breakstmt();
      break;
    case RETURN:
      Return();
      break;
    case CONTINUE:
      Continuestmt();
      break;
    case RETRY:
      Retrystmt();
      break;
    case EXIT:
      Exitstmt();
      break;
    case FOR:
      Forstmt();
      break;
    case FOREACH:
      Foreachstmt();
      break;
    case WHILE:
      Whilestmt();
      break;
    case LOOP:
      Loopstmt();
      break;
    case GOTO:
      Gotostmt();
      break;
    case IF:
      Ifstmt();
      break;
    case SWITCH:
      Switchstmt();
      break;
    case FUNCTION:
    case TYPE:
    case PROCEDURE:
    case CONSTANT:
    case ENUM:
    case IDENTIFIER:
    case 70:
      Look();
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Statementblock() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BREAK:
      Breakstmt();
      break;
    case RETURN:
      Return();
      break;
    case CONTINUE:
      Continuestmt();
      break;
    case RETRY:
      Retrystmt();
      break;
    case EXIT:
      Exitstmt();
      break;
    case FOR:
      Forstmt();
      break;
    case FOREACH:
      Foreachstmt();
      break;
    case WHILE:
      Whilestmt();
      break;
    case LOOP:
      Loopstmt();
      break;
    case GOTO:
      Gotostmt();
      break;
    case IF:
      Ifstmt();
      break;
    case SWITCH:
      Switchstmt();
      break;
    case CONSTANT:
    case ENUM:
    case IDENTIFIER:
    case 70:
      Lookblock();
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Look() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 70:
      jj_consume_token(70);
      Expression();
      break;
    default:
      jj_la1[4] = jj_gen;
      if (jj_2_1(2)) {
        Assignwithop();
      } else if (jj_2_2(2)) {
        Call();
      } else if (jj_2_3(2)) {
        Assignmono();
      } else if (jj_2_4(2)) {
        Assignmulti();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROCEDURE:
          Procdeclare();
          break;
        case FUNCTION:
          Funcdeclare();
          break;
        case TYPE:
          Typedeclare();
          break;
        default:
          jj_la1[5] = jj_gen;
          if (jj_2_5(2)) {
            Vardeclare();
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case CONSTANT:
              Constdeclare();
              break;
            case ENUM:
              Enumdeclare();
              break;
            default:
              jj_la1[6] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
  }

  static final public void Lookblock() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 70:
      jj_consume_token(70);
      Expression();
      break;
    default:
      jj_la1[7] = jj_gen;
      if (jj_2_6(2)) {
        Assignwithop();
      } else if (jj_2_7(2)) {
        Call();
      } else if (jj_2_8(2)) {
        Vardeclare();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CONSTANT:
          Constdeclare();
          break;
        case ENUM:
          Enumdeclare();
          break;
        default:
          jj_la1[8] = jj_gen;
          if (jj_2_9(2)) {
            Assignmono();
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case IDENTIFIER:
              Assignmulti();
              break;
            default:
              jj_la1[9] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
  }

  static final public void Breakstmt() throws ParseException {
    jj_consume_token(BREAK);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        Stringlit();
        break;
      case ATOMINTEGER:
      case ATOMREAL:
      case ATOMBINARY:
      case ATOMOCTAL:
      case ATOMDECIMAL:
      case ATOMHEXADECIMAL:
        Atomexpr();
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
  }

  static final public void Continuestmt() throws ParseException {
    jj_consume_token(CONTINUE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        Stringlit();
        break;
      case ATOMINTEGER:
      case ATOMREAL:
      case ATOMBINARY:
      case ATOMOCTAL:
      case ATOMDECIMAL:
      case ATOMHEXADECIMAL:
        Atomexpr();
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  static final public void Retrystmt() throws ParseException {
    jj_consume_token(RETRY);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        Stringlit();
        break;
      case ATOMINTEGER:
      case ATOMREAL:
      case ATOMBINARY:
      case ATOMOCTAL:
      case ATOMDECIMAL:
      case ATOMHEXADECIMAL:
        Atomexpr();
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  }

  static final public void Exitstmt() throws ParseException {
    jj_consume_token(EXIT);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        Stringlit();
        break;
      case ATOMINTEGER:
      case ATOMREAL:
      case ATOMBINARY:
      case ATOMOCTAL:
      case ATOMDECIMAL:
      case ATOMHEXADECIMAL:
        Atomexpr();
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
  }

  static final public void Stringlit() throws ParseException {
    jj_consume_token(STRING);
  }

  static final public void Forstmt() throws ParseException {
    jj_consume_token(FOR);
    Foridx();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      Labelstmt();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    jj_consume_token(DO);
        flagBranchStmt++;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(FOR);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
        flagBranchStmt--;
  }

  static final public void Foridx() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(71);
    Expression();
    jj_consume_token(TO);
    Expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BY:
      jj_consume_token(BY);
      Expression();
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
  }

  static final public void Foreachstmt() throws ParseException {
    jj_consume_token(FOREACH);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(72);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      jj_consume_token(IDENTIFIER);
      break;
    case 88:
      Seqexpr();
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(73);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      Labelstmt();
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(DO);
        flagBranchStmt++;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(FOREACH);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
        flagBranchStmt--;
  }

  static final public void Labelstmt() throws ParseException {
    jj_consume_token(LABEL);
    Stringlit();
  }

  static final public void Whilestmt() throws ParseException {
    jj_consume_token(WHILE);
    Expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      Labelstmt();
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
    jj_consume_token(DO);
        flagBranchStmt++;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(WHILE);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
        flagBranchStmt--;
  }

  static final public void Loopstmt() throws ParseException {
    jj_consume_token(LOOP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      Labelstmt();
      break;
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    jj_consume_token(DO);
        flagBranchStmt++;
    Block();
    jj_consume_token(UNTIL);
    Expression();
    jj_consume_token(END);
    jj_consume_token(LOOP);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
        flagBranchStmt--;
  }

  static final public void Gotostmt() throws ParseException {
    jj_consume_token(GOTO);
    Labelstmt();
  }

  static final public void Ifstmt() throws ParseException {
    Iftest();
    label_3:
    while (true) {
      if (jj_2_10(2)) {
        ;
      } else {
        break label_3;
      }
      Elsif();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      Else();
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(IF);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
        flagBranchStmt--;
  }

  static final public void Iftest() throws ParseException {
    jj_consume_token(IF);
    Expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      Labelstmt();
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(THEN);
        flagBranchStmt++;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[30] = jj_gen;
      ;
    }
  }

  static final public void Elsif() throws ParseException {
    jj_consume_token(ELSIF);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
    Expression();
    jj_consume_token(THEN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[31] = jj_gen;
      ;
    }
  }

  static final public void Else() throws ParseException {
    jj_consume_token(ELSE);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[32] = jj_gen;
      ;
    }
  }

  static final public void Switchstmt() throws ParseException {
    Switchtest();
    label_4:
    while (true) {
      Case();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CASE:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_4;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      Caseelse();
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(SWITCH);
        removeNivel(TabelaAux, flagBranchStmt);
        listaChaves.clear();
        flagBranchStmt--;
  }

  static final public void Switchtest() throws ParseException {
    jj_consume_token(SWITCH);
    Expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      Labelstmt();
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }
    jj_consume_token(DO);
        flagBranchStmt++;
  }

  static final public void Case() throws ParseException {
    jj_consume_token(CASE);
    Caselist();
    jj_consume_token(THEN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[36] = jj_gen;
      ;
    }
  }

  static final public void Caselist() throws ParseException {
    Expression();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 74:
        ;
        break;
      default:
        jj_la1[37] = jj_gen;
        break label_5;
      }
      jj_consume_token(74);
      Expression();
    }
  }

  static final public void Caseelse() throws ParseException {
    jj_consume_token(ELSE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
  }

  static final public void Assignmono() throws ParseException {
    Varexp();
    jj_consume_token(71);
    Expression();
  }

  static final public void Assignmulti() throws ParseException {
    Varexp();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 74:
        ;
        break;
      default:
        jj_la1[39] = jj_gen;
        break label_6;
      }
      jj_consume_token(74);
      Varexp();
    }
    jj_consume_token(71);
    Expression();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 74:
        ;
        break;
      default:
        jj_la1[40] = jj_gen;
        break label_7;
      }
      jj_consume_token(74);
      Expression();
    }
  }

  static final public void Assignwithop() throws ParseException {
    Varexp();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 75:
      jj_consume_token(75);
      break;
    case 76:
      jj_consume_token(76);
      break;
    case 77:
      jj_consume_token(77);
      break;
    case 78:
      jj_consume_token(78);
      break;
    case 79:
      jj_consume_token(79);
      break;
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(71);
    Expression();
  }

  static final public void Return() throws ParseException {
    if(flagBranchStmt == 0)
        nReturn++;

    procedureReturn++;
    jj_consume_token(RETURN);
    Expression();
  }

  static final public void Vardeclare() throws ParseException {
    Token t;
    t = jj_consume_token(IDENTIFIER);
    Identlist();
        atualizaVariavel(t, "var");
  }

  static final public void Identlist() throws ParseException {
    Ident();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 74:
        ;
        break;
      default:
        jj_la1[42] = jj_gen;
        break label_8;
      }
      jj_consume_token(74);
      Ident();
    }
  }

  static final public void Ident() throws ParseException {
    Token t;
    t = jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 71:
      jj_consume_token(71);
      Expression();
      break;
    default:
      jj_la1[43] = jj_gen;
      ;
    }
        Dado tmp = new Dado();
        tmp.setIdentificador(t.toString());

        if(valor != null && flagCategoria.equals("constant")) {
            tmp.setValor(valor.toString());
            valor = null;
        }

        if(flagBranchStmt == 0) {
            tmp.setNivel(nivelCorrente);
            insereTabela(TabelaSimb, tmp);
        }
        else {
            if(naoDeclarado(TabelaSimb, t.toString(), nivelCorrente)) {
                tmp.setNivel(flagBranchStmt);
                insereTabela(TabelaAux, tmp);
            }
            else {
                System.out.println("Erro! Identificador \u005c"" + dado.getIdentificador() +  "\u005c" j\u00e1 declarado");
            }
        }
  }

  static final public void Constdeclare() throws ParseException {
    Token t;
    flagCategoria = "constant";
    t = jj_consume_token(CONSTANT);
    Identlist();
        if(flagBranchStmt == 0)
            atualizaCategoria(TabelaSimb, t.toString());
        else
            atualizaCategoria(TabelaAux, t.toString());
        listaChaves.clear();
        flagCategoria = "";
  }

  static final public void Enumdeclare() throws ParseException {
    jj_consume_token(ENUM);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BY:
    case IDENTIFIER:
      Enumval();
      break;
    case TYPE:
      Enumtype();
      break;
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Enumval() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BY:
      jj_consume_token(BY);
      Enumdelta();
      break;
    default:
      jj_la1[45] = jj_gen;
      ;
    }
    Identlist();
        Integer chave = buscaTipo(TabelaSimb, "integer");
        if(flagBranchStmt == 0) {
            atualizaCategoria(TabelaSimb, "constant");
            atualizaTipo(TabelaSimb, chave);
        }
        else {
            atualizaCategoria(TabelaAux, "constant");
            atualizaTipo(TabelaAux, chave);
        }
        listaChaves.clear();
        flagCategoria = "";
  }

  static final public void Enumdelta() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 75:
    case 76:
    case 77:
    case 78:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 75:
        jj_consume_token(75);
        break;
      case 76:
        jj_consume_token(76);
        break;
      case 78:
        jj_consume_token(78);
        break;
      case 77:
        jj_consume_token(77);
        break;
      default:
        jj_la1[46] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[47] = jj_gen;
      ;
    }
    Expression();
  }

  static final public void Enumtype() throws ParseException {
    Integer chave;
    Dado dado;
    Token t;
    jj_consume_token(TYPE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BY:
      jj_consume_token(BY);
      Enumdelta();
      break;
    default:
      jj_la1[48] = jj_gen;
      ;
    }
    t = jj_consume_token(IDENTIFIER);
        // Neste caso precisa ser do tipo inteiro
        chave = buscaTipo(TabelaSimb, "integer");

        if(chave > -1) {
            dado = new Dado();
            dado.setIdentificador(t.toString());
            dado.setNivel(nivelCorrente);
            dado.setCategoria("type");
            dado.setTipo(chave);

            if(flagBranchStmt == 0)
                insereTabela(TabelaSimb, dado);
            else
                insereTabela(TabelaAux, dado);
        }
        else {
            System.out.println("Erro! Palavra reservada \u005c"" + t.toString() + "\u005c" n\u00e3o existe");
        }
        listaChaves.clear();
    Identlist();
        atualizaVariavel(t, "constant");
    jj_consume_token(END);
    jj_consume_token(TYPE);
  }

  static final public void Procdeclare() throws ParseException {
    Dado dado;
    Token t, s;
    t = jj_consume_token(PROCEDURE);
    s = jj_consume_token(IDENTIFIER);
        dado = new Dado();
        dado.setIdentificador(s.toString());
        dado.setNivel(nivelCorrente);
        dado.setCategoria(t.toString());

        insereTabela(TabelaSimb, dado);
        listaChaves.clear();
        nivelCorrente++;
    jj_consume_token(72);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      Paramlist();
      break;
    default:
      jj_la1[49] = jj_gen;
      ;
    }
    jj_consume_token(73);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[50] = jj_gen;
      ;
    }
        dado.setNParametros(listaChaves.size());
    jj_consume_token(END);
    jj_consume_token(PROCEDURE);
        if(procedureReturn > 0)
            System.out.println("Erro! Procedure n\u00e3o pode ter return!!");

        procedureReturn = 0;
        removeNivel(TabelaSimb, nivelCorrente);
        listaChaves.clear();
        nivelCorrente--;
  }

  static final public void Paramlist() throws ParseException {
    Parameter();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 74:
        ;
        break;
      default:
        jj_la1[51] = jj_gen;
        break label_9;
      }
      jj_consume_token(74);
      Parameter();
    }
  }

  static final public void Parameter() throws ParseException {
    Dado dado;
    Token t, n;
    t = jj_consume_token(IDENTIFIER);
    n = jj_consume_token(IDENTIFIER);
        Integer chave = buscaTipo(TabelaSimb, t.toString());

        if(chave > -1) {
            dado = new Dado();
            dado.setIdentificador(n.toString());
            dado.setNivel(nivelCorrente);
            dado.setTipo(chave);
            dado.setCategoria("parameter");

            insereTabela(TabelaSimb, dado);
        }
        else {
            System.out.println("Erro! Palavra reservada \u005c"" + t.toString() + "\u005c" n\u00e3o existe");
        }
  }

  static final public void Funcdeclare() throws ParseException {
    Dado dado;
    Token t, s;
    t = jj_consume_token(FUNCTION);
    s = jj_consume_token(IDENTIFIER);
        dado = new Dado();
        dado.setIdentificador(s.toString());
        dado.setNivel(nivelCorrente);
        dado.setCategoria(t.toString());

        insereTabela(TabelaSimb, dado);
        listaChaves.clear();
        nivelCorrente++;
    jj_consume_token(72);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      Paramlist();
        dado.setNParametros(listaChaves.size());
      break;
    default:
      jj_la1[52] = jj_gen;
      ;
    }
    jj_consume_token(73);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[53] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(FUNCTION);
        if(nReturn < 1)
            System.out.println("Erro! Function precisa de retorno!");
        nReturn = 0;
        removeNivel(TabelaSimb, nivelCorrente);
        listaChaves.clear();
        nivelCorrente--;
  }

  static final public void Typedeclare() throws ParseException {
    Token t, s;
    s = jj_consume_token(TYPE);
    t = jj_consume_token(IDENTIFIER);
        dado = new Dado();
        dado.setIdentificador(t.toString());
        dado.setNivel(nivelCorrente);
        dado.setCategoria(s.toString());

        insereTabela(TabelaSimb, dado);
        listaChaves.clear();
        nivelCorrente++;
    jj_consume_token(72);
    Parameter();
    jj_consume_token(73);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case BREAK:
    case RETURN:
    case FOR:
    case FOREACH:
    case CONSTANT:
    case ENUM:
    case SWITCH:
    case CONTINUE:
    case RETRY:
    case EXIT:
    case LOOP:
    case GOTO:
    case IDENTIFIER:
    case 70:
      Block();
      break;
    default:
      jj_la1[54] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(TYPE);
        if(nReturn < 1)
            System.out.println("Erro! Type precisa de retorno!");
        nReturn = 0;

        removeNivel(TabelaSimb, nivelCorrente);
        listaChaves.clear();
        nivelCorrente--;
  }

  static final public void Expression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 88:
      Seqexpr();
      break;
    case STRING:
    case IDENTIFIER:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
    case BIN:
    case 72:
      Binexpr();
      break;
    default:
      jj_la1[55] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Binexpr() throws ParseException {
    Relexpr();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
      case XOR:
        ;
        break;
      default:
        jj_la1[56] = jj_gen;
        break label_10;
      }
      Binop();
      Relexpr();
    }
  }

  static final public void Binop() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
      jj_consume_token(AND);
      break;
    case OR:
      jj_consume_token(OR);
      break;
    case XOR:
      jj_consume_token(XOR);
      break;
    default:
      jj_la1[57] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Relexpr() throws ParseException {
    Concatexpr();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 71:
      case 80:
      case 81:
      case 82:
      case 83:
      case 84:
        ;
        break;
      default:
        jj_la1[58] = jj_gen;
        break label_11;
      }
      Relop();
      Concatexpr();
    }
  }

  static final public void Relop() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 80:
      jj_consume_token(80);
      break;
    case 81:
      jj_consume_token(81);
      break;
    case 82:
      jj_consume_token(82);
      break;
    case 83:
      jj_consume_token(83);
      break;
    case 71:
      jj_consume_token(71);
      break;
    case 84:
      jj_consume_token(84);
      break;
    default:
      jj_la1[59] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Concatexpr() throws ParseException {
    Sumsubexpr();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 79:
        ;
        break;
      default:
        jj_la1[60] = jj_gen;
        break label_12;
      }
      Concat();
      Sumsubexpr();
    }
  }

  static final public void Concat() throws ParseException {
    jj_consume_token(79);
  }

  static final public void Sumsubexpr() throws ParseException {
    Multidivexpr();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 75:
      case 76:
        ;
        break;
      default:
        jj_la1[61] = jj_gen;
        break label_13;
      }
      Sumsub();
      Multidivexpr();
    }
  }

  static final public void Sumsub() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 75:
      jj_consume_token(75);
      break;
    case 76:
      jj_consume_token(76);
      break;
    default:
      jj_la1[62] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Multidivexpr() throws ParseException {
    Unaryexpr();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 77:
      case 78:
        ;
        break;
      default:
        jj_la1[63] = jj_gen;
        break label_14;
      }
      Multidiv();
      Unaryexpr();
    }
  }

  static final public void Multidiv() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 78:
      jj_consume_token(78);
      break;
    case 77:
      jj_consume_token(77);
      break;
    default:
      jj_la1[64] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Unaryexpr() throws ParseException {
    Lastexpr();
    if (jj_2_11(2)) {
      Unaryop();
      Lastexpr();
    } else {
      ;
    }
  }

  static final public void Unaryop() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      break;
    case 76:
      jj_consume_token(76);
      break;
    case 75:
      jj_consume_token(75);
      break;
    default:
      jj_la1[65] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Lastexpr() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
      Atomexpr();
      break;
    case STRING:
      Stringlit();
      break;
    case BIN:
      jj_consume_token(BIN);
      break;
    case 72:
      jj_consume_token(72);
      Expression();
      jj_consume_token(73);
      break;
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 72:
      case 85:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 85:
          Variable();
          break;
        case 72:
          Callf();
          break;
        default:
          jj_la1[66] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[67] = jj_gen;
        ;
      }
        naoDeclaradoFluxo(t);
      break;
    default:
      jj_la1[68] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Variable() throws ParseException {
    if (jj_2_12(3)) {
      Slice();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 85:
        label_15:
        while (true) {
          jj_consume_token(85);
          Expression();
          jj_consume_token(86);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 85:
            ;
            break;
          default:
            jj_la1[69] = jj_gen;
            break label_15;
          }
        }
        break;
      default:
        jj_la1[70] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void Varexp() throws ParseException {
    Token t;
    t = jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 85:
      if (jj_2_13(3)) {
        Slice();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 85:
          label_16:
          while (true) {
            jj_consume_token(85);
            Expression();
            jj_consume_token(86);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case 85:
              ;
              break;
            default:
              jj_la1[71] = jj_gen;
              break label_16;
            }
          }
          break;
        default:
          jj_la1[72] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
    default:
      jj_la1[73] = jj_gen;
      ;
    }
        naoDeclaradoFluxo(t);
  }

  static final public void Slice() throws ParseException {
    jj_consume_token(85);
    Expression();
    jj_consume_token(87);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case IDENTIFIER:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
    case BIN:
    case 72:
    case 88:
      Expression();
      break;
    case DOLAR:
      jj_consume_token(DOLAR);
      break;
    default:
      jj_la1[74] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(86);
  }

  static final public void Seqexpr() throws ParseException {
    jj_consume_token(88);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOLAR:
    case STRING:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
    case 88:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOLAR:
        jj_consume_token(DOLAR);
        break;
      case STRING:
      case ATOMINTEGER:
      case ATOMREAL:
      case ATOMBINARY:
      case ATOMOCTAL:
      case ATOMDECIMAL:
      case ATOMHEXADECIMAL:
      case 88:
        Objexpr();
        label_17:
        while (true) {
          if (jj_2_14(2)) {
            ;
          } else {
            break label_17;
          }
          jj_consume_token(74);
          Objexpr();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 74:
          jj_consume_token(74);
          jj_consume_token(DOLAR);
          break;
        default:
          jj_la1[75] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[76] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[77] = jj_gen;
      ;
    }
    jj_consume_token(89);
  }

  static final public void Call() throws ParseException {
    jj_consume_token(IDENTIFIER);
    jj_consume_token(72);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case IDENTIFIER:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
    case BIN:
    case 72:
    case 88:
      Arglist();
      break;
    default:
      jj_la1[78] = jj_gen;
      ;
    }
    jj_consume_token(73);
  }

  static final public void Callf() throws ParseException {
    jj_consume_token(72);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case IDENTIFIER:
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
    case BIN:
    case 72:
    case 88:
      Arglist();
      break;
    default:
      jj_la1[79] = jj_gen;
      ;
    }
    jj_consume_token(73);
  }

  static final public void Arglist() throws ParseException {
    Expression();
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 74:
        ;
        break;
      default:
        jj_la1[80] = jj_gen;
        break label_18;
      }
      jj_consume_token(74);
      Expression();
    }
  }

  static final public void Objexpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ATOMINTEGER:
    case ATOMREAL:
    case ATOMBINARY:
    case ATOMOCTAL:
    case ATOMDECIMAL:
    case ATOMHEXADECIMAL:
      Atomexpr();
      break;
    case 88:
      Seqexpr();
      break;
    case STRING:
      jj_consume_token(STRING);
      break;
    default:
      jj_la1[81] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Atomexpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ATOMINTEGER:
      jj_consume_token(ATOMINTEGER);
      break;
    case ATOMREAL:
      jj_consume_token(ATOMREAL);
      break;
    case ATOMBINARY:
      jj_consume_token(ATOMBINARY);
      break;
    case ATOMOCTAL:
      jj_consume_token(ATOMOCTAL);
      break;
    case ATOMDECIMAL:
      jj_consume_token(ATOMDECIMAL);
      break;
    case ATOMHEXADECIMAL:
      jj_consume_token(ATOMHEXADECIMAL);
      break;
    default:
      jj_la1[82] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/* Funcoes Auxiliares */
  static final public boolean naoDeclarado(Hashtable<Integer, Dado> tabela, String IdProcurado, Integer NivelProcurado) throws ParseException {
    Enumeration t = tabela.keys();
    Integer chave;
    Dado dado;
        while (t.hasMoreElements()) {
            chave = (Integer)t.nextElement();
            dado = tabela.get(chave);

            if(dado.getIdentificador().equals(IdProcurado) && dado.getNivel() == NivelProcurado){
                {if (true) return false;}/* ja existe na tabela*/
            }
        }
        /* pode ser adicionado futuramente na tabela */
        {if (true) return true;}
    throw new Error("Missing return statement in function");
  }

  static final public void naoDeclaradoFluxo(Token t) throws ParseException {
        if(naoDeclarado(TabelaSimb, t.toString(), nivelCorrente)) {
            int i = 0;
            for(i = flagBranchStmt; naoDeclarado(TabelaAux, t.toString(), i) && i > 0; i--);

            if(i == 0)
                System.out.println("Erro! Vari\u00e1vel \u005c"" + t.toString() + "\u005c" n\u00e3o declarada no nivel atual!");
        }
  }

  static final public void insereTabela(Hashtable<Integer, Dado> tabela, Dado dado) throws ParseException {
        if(naoDeclarado(tabela, dado.getIdentificador(), dado.getNivel())){
            tabela.put(indexTabela, dado);
            listaChaves.add(indexTabela);
            indexTabela++;
        }
        else {
            System.out.println("Erro! Identificador \u005c"" + dado.getIdentificador() +  "\u005c" j\u00e1 declarado no n\u00edvel atual");
        }
  }

  static final public Integer buscaTipo(Hashtable<Integer, Dado> tabela, String Identifier) throws ParseException {
    Integer chave;
    Enumeration elemento = tabela.keys();
    Dado dado;
        while(elemento.hasMoreElements()) {
            chave = (Integer) elemento.nextElement();
            dado = tabela.get(chave);

            if(dado.getIdentificador().equals(Identifier) && dado.getCategoria().equals("type"))
                {if (true) return chave;}
        }
        {if (true) return -1;}
    throw new Error("Missing return statement in function");
  }

  static final public void imprimeTabela(Hashtable<Integer, Dado> tabela) throws ParseException {
    Integer chave;
    Enumeration elemento = tabela.keys();
    Dado dado;
        System.out.printf("%-4s%-10s%-6s%-10s%-6s%-6s%-6s%-6s%-10s%-10s\u005cn", "ID", "IDENT", "NIVEL", "CATEGORIA", "TIPO", "END", "NBYTE", "VALOR", "CLASST", "NPARAM");
        System.out.println("-------------------------------------------------------------------------");
        while(elemento.hasMoreElements()) {
            chave = (Integer) elemento.nextElement();
            dado = tabela.get(chave);

            System.out.printf("%-4s%-10s%-6s%-10s%-6s%-6s%-6s%-6s%-10s%-10s\u005cn",
                              chave, dado.getIdentificador(), dado.getNivel(),
                              dado.getCategoria(), dado.getTipo(), dado.getEndereco(),
                              dado.getNBytes(), dado.getValor(), dado.getClasseTransf(),
                              dado.getNParametros());
        }

        System.out.println("");
  }

  static final public void atualizaCategoria(Hashtable<Integer, Dado> tabela,String Categoria) throws ParseException {
    Dado dado;
        for(Integer chave : listaChaves)
        {
            dado = tabela.get(chave);
            dado.setCategoria(Categoria);
        }
  }

  static final public void atualizaTipo(Hashtable<Integer, Dado> tabela, Integer Tipo) throws ParseException {
    Dado dado;
        for(Integer chave : listaChaves)
        {
            dado = tabela.get(chave);
            dado.setTipo(Tipo);
        }
  }

  static final public void atualizaNParam(Hashtable<Integer, Dado> tabela, Integer n) throws ParseException {
    Dado dado;
        for(Integer chave : listaChaves)
        {
            dado = tabela.get(chave);
            dado.setNParametros(n);
        }
  }

  static final public void atualizaNBytes(Hashtable<Integer, Dado> tabela, Integer nbytes) throws ParseException {
    Dado dado;
        for(Integer chave : listaChaves)
        {
            dado = tabela.get(chave);
            dado.setNBytes(nbytes);
        }
  }

  static final public void removeNivel(Hashtable<Integer, Dado> tabela, Integer nivel) throws ParseException {
    Integer chave;
    Enumeration t = tabela.keys();
    Dado dado;
        while(t.hasMoreElements())
        {
            chave = (Integer) t.nextElement();
            dado = tabela.get(chave);

            if(dado.getNivel() == nivel) {
                tabela.remove(chave);
            }
        }
  }

  static final public void removeChaves(Hashtable<Integer, Dado> tabela, ArrayList<Integer> chaves) throws ParseException {
        for(Integer chave : chaves) {
            tabela.remove(chave);
        }
  }

  static final public void atualizaVariavel(Token t, String Categoria) throws ParseException {
        Hashtable <Integer, Dado> tabela = TabelaSimb;
        Integer chave = buscaTipo(TabelaSimb, t.toString());

        if(chave == -1) {
            tabela = TabelaAux;
            chave = buscaTipo(tabela, t.toString());
        }

        if(chave > -1) {
            Dado builtin = tabela.get(chave);
            if(flagBranchStmt == 0) {
                atualizaTipo(TabelaSimb, chave);
                atualizaNBytes(TabelaSimb, builtin.getNBytes());
                atualizaCategoria(TabelaSimb, Categoria);
            }
            else {
                atualizaTipo(TabelaAux, chave);
                atualizaNBytes(TabelaAux, builtin.getNBytes());
                atualizaCategoria(TabelaAux, Categoria);
            }
        }
        else {
            System.out.println("Erro! O tipo \u005c"" + t.toString() + "\u005c" n\u00e3o existe!\u005cn");

            if(flagBranchStmt == 0)
                removeChaves(TabelaSimb, listaChaves);
            else
                removeChaves(TabelaAux, listaChaves);
        }
        listaChaves.clear();
  }

  static final public void initBuiltins() throws ParseException {
        //Atom
        Dado atom = new Dado();
        atom.setIdentificador("atom");
        atom.setCategoria("type");
        atom.setTipo(indexTabela);
        // FIXME: Definir o tamanho em bytes
        atom.setNBytes(5);
        atom.setNivel(0);

        insereTabela(TabelaSimb, atom);

        //Integer
        Dado integer = new Dado();
        integer.setIdentificador("integer");
        integer.setCategoria("type");
        integer.setTipo(indexTabela);
        // FIXME: Definir o tamanho em bytes
        integer.setNBytes(4);
        integer.setNivel(0);

        insereTabela(TabelaSimb, integer);

        listaChaves.clear();
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_3_2() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_3R_62()) return true;
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) return true;
    }
    return false;
  }

  static private boolean jj_3R_64() {
    if (jj_3R_66()) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_3R_25()) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_scan_token(79)) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_38()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_3R_56()) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_3R_45()) return true;
    return false;
  }

  static private boolean jj_3R_57() {
    if (jj_3R_59()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_60()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(76)) {
    jj_scanpos = xsp;
    if (jj_scan_token(75)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_3R_53()) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_3R_26()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_62() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(78)) {
    jj_scanpos = xsp;
    if (jj_scan_token(77)) return true;
    }
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_3R_57()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_58()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_63()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_3R_54()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_55()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_61() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(76)) return true;
    }
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_scan_token(72)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    }
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_3R_50()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_52()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_56() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(80)) {
    jj_scanpos = xsp;
    if (jj_scan_token(81)) {
    jj_scanpos = xsp;
    if (jj_scan_token(82)) {
    jj_scanpos = xsp;
    if (jj_scan_token(83)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) {
    jj_scanpos = xsp;
    if (jj_scan_token(84)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_47()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_49()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_3R_42()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_scan_token(61)) {
    jj_scanpos = xsp;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_scan_token(74)) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_3R_29()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(76)) {
    jj_scanpos = xsp;
    if (jj_scan_token(77)) {
    jj_scanpos = xsp;
    if (jj_scan_token(78)) {
    jj_scanpos = xsp;
    if (jj_scan_token(79)) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_30()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(71)) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_3R_29()) return true;
    if (jj_scan_token(71)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(ELSIF)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_scan_token(74)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_scan_token(85)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    Token xsp;
    if (jj_3R_46()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_46()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_69() {
    if (jj_scan_token(85)) return true;
    return false;
  }

  static private boolean jj_3R_68() {
    Token xsp;
    if (jj_3R_69()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_69()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_3R_51()) return true;
    }
    return false;
  }

  static private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(63)) {
    jj_scanpos = xsp;
    if (jj_scan_token(64)) {
    jj_scanpos = xsp;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(68)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_3R_42()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_scan_token(61)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_scan_token(88)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_48()) jj_scanpos = xsp;
    if (jj_scan_token(89)) return true;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_scan_token(72)) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(72)) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_scan_token(85)) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(87)) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    if (jj_3R_67()) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_66() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) return true;
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public TrabalhoSemanticoTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[83];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x38bff400,0x38b1f400,0x38bff400,0x38b1f400,0x0,0xe0000,0x300000,0x0,0x300000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x38b1f400,0x400000,0x0,0x0,0x0,0x38b1f400,0x0,0x38b1f400,0x0,0x200,0x0,0x38b1f400,0x38b1f400,0x38b1f400,0x4000000,0x200,0x0,0x38b1f400,0x0,0x38b1f400,0x0,0x0,0x0,0x0,0x0,0x440000,0x400000,0x0,0x0,0x400000,0x0,0x38b1f400,0x0,0x0,0x38b1f400,0x38b1f400,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x40000600,0x40000600,0x40000600,0x40000600,0x0,0x0,0x0,0x0,0x0,0x40000000,0xa0000000,0xa0000000,0xa0000000,0xa0000000,0xa0000000,0xa0000000,0xa0000000,0xa0000000,0x10000,0x40000600,0x0,0x40000000,0x40000000,0x10000,0x40000600,0x10000,0x40000600,0x10000,0x0,0x10000,0x40000600,0x40000600,0x40000600,0x0,0x0,0x10000,0x40000600,0x0,0x40000600,0x0,0x0,0x0,0x0,0x0,0x40000000,0x0,0x0,0x0,0x0,0x40000000,0x40000600,0x0,0x40000000,0x40000600,0x40000600,0xe0000000,0x7000,0x7000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x800,0x0,0x0,0xe0000000,0x0,0x0,0x0,0x0,0x0,0xe0040000,0x0,0xa0040000,0xa0040000,0xe0000000,0xe0000000,0x0,0xa0000000,0x80000000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x40,0x40,0x40,0x40,0x40,0x0,0x0,0x40,0x0,0x0,0x1f,0x1f,0x1f,0x1f,0x1f,0x1f,0x1f,0x1f,0x0,0x40,0x0,0x0,0x1000000,0x0,0x40,0x0,0x40,0x0,0x0,0x0,0x40,0x40,0x40,0x0,0x0,0x0,0x40,0x400,0x40,0x400,0x400,0xf800,0x400,0x80,0x0,0x0,0x7800,0x7800,0x0,0x0,0x40,0x400,0x0,0x40,0x40,0x100013f,0x0,0x0,0x1f0080,0x1f0080,0x8000,0x1800,0x1800,0x6000,0x6000,0x1800,0x200100,0x200100,0x13f,0x200000,0x200000,0x200000,0x200000,0x200000,0x100013f,0x400,0x100001f,0x100001f,0x100013f,0x100013f,0x400,0x100001f,0x1f,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[14];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public TrabalhoSemantico(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TrabalhoSemantico(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TrabalhoSemanticoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public TrabalhoSemantico(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TrabalhoSemanticoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public TrabalhoSemantico(TrabalhoSemanticoTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(TrabalhoSemanticoTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 83; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[90];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 83; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 90; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 14; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
